<a href="https://colab.research.google.com/github/Kayan-dev/data-science/blob/new_branch/0_Fundamentals_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The most fundamental concepts of tensors using TensorFlow

Specifically, to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating Tensors
* Tensors & NumPy
& Using @tf.function ( a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself

In [4]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)


2.5.0


In [5]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check number of dimensions of tensor (ndim)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [10]:
# Create a matrix (with +1 dimensions)
matrix = tf.constant([[5,8],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [13]:
matrix = tf.constant([[5,8,12],
                     [7,10,15]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  8, 12],
       [ 7, 10, 15]], dtype=int32)>

In [14]:
matrix.ndim

2

In [16]:
matrix = tf.constant([[5,8,12],
                     [7,10,15],
                      [4,8,10]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5,  8, 12],
       [ 7, 10, 15],
       [ 4,  8, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [18]:
another_matrix = tf.constant([[5.,8.,],
                              [4.,5.],
                              [8.,10.]], dtype=tf.float16) # Specify the dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 5.,  8.],
       [ 4.,  5.],
       [ 8., 10.]], dtype=float16)>

In [19]:
another_matrix = tf.constant([[5.,8.,],
                              [4.,5.],
                              [8.,10.]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 5.,  8.],
       [ 4.,  5.],
       [ 8., 10.]], dtype=float32)>

In [20]:
dimension_matrix = tf.constant([10,12])
dimension_matrix

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 12], dtype=int32)>

In [21]:
dimension_matrix.ndim

1

In [25]:
# Another tensor with different shape
tensor = tf.constant([[[1,2,3],
                       [2,3,4]],
                       
                       [[3,4,5],
                       [4,5,6]],
                      
                      [[5,6,7],
                       [6,7,8]],
                      
                      [[7,8,9],
                       [9,10,12]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 3,  4,  5],
        [ 4,  5,  6]],

       [[ 5,  6,  7],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 9, 10, 12]]], dtype=int32)>

In [23]:
tensor.ndim

3

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

1. 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
2. 3 is the number of colour channels of the image (red, green blue).
3. 32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):




* scalar: a single number.
* vector: a number with direction (e.g. wind speed with direction).
* matrix: a 2-dimensional array of numbers.
* tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

In [26]:
# Create a variable tensor and a constant tensor
variable_tensor = tf.Variable([4,8])
constant_tensor = tf.constant([5,10])
variable_tensor,constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10], dtype=int32)>)

In [27]:
# Change the tensor value
variable_tensor[0].assign(5)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 8], dtype=int32)>

In [28]:
# Try to change the unchangable tensor
constant_tensor[0] = 7

TypeError: ignored

In [29]:
constant_tensor[0].assign(7)

AttributeError: ignored

##As you can see it cannot change for an unchangable tensor using tf.constant but you can change it when using tf.Variable

## Creating Random Tensors

We can create random tensors by using the tf.random.Generator class.

In [31]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [32]:
# When we change the seed, what happens then?

# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# As you can see it is False i.e. not equal when the seed differs

In [34]:
# You will want too shuffle the order of your tensors to prevent 
# your model to learn the order of the data and thus overfit

# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [35]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [38]:
tf.random.shuffle(not_shuffled, seed=42), tf.random.shuffle(not_shuffled, seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [10,  7],
        [ 2,  5]], dtype=int32)>)

In [37]:
### If we want to shuffle our

### you can change NumPy array into tensors

In [42]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [43]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>